[package]
name = "nt"
version = "0.1.0"
edition = "2021"
description = "minimal snippet manager for the terminal"

[dependencies]
copypasta = "0.8.1"
clap = { version = "3.2.8", features = ["cargo"] }
dirs = "4.0.0"
json = "0.12.4"